name: adventofcode
version: 0.1.0.0
github: "r-a303931/adventofcode"
license: BSD3
author: "Andrew Rioux"
maintainer: "rioux.d.andrew@gmail.com"
copyright: "AGPL"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/r-a303931/adventofcode#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  adventofcode-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode
      - time

tests:
  adventofcode-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode
